<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="WorkWithData.aspx.cs" Inherits="WebWithSql.WorkWithData" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <link href="Styles/site.css" rel="stylesheet" />
</head>
<body>
    <form id="formWorkWithData" runat="server">
        <!-- Add User Form -->
        <div>
            <table>
                <thead>
                    <tr>
                        <th>User Name:</th>
                        <th>E-mail</th>
                        <th>Date Of Birth</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <!-- New User Name -->
                        <td>
                            <asp:TextBox ID="txtUserName" runat="server"></asp:TextBox>
                        </td>
                        <!-- E-mail -->
                        <td>
                            <asp:TextBox ID="txtEmail" runat="server" TextMode="Email"></asp:TextBox>
                        </td>
                        <!-- Date Of Birth -->
                        <td>
                            <asp:TextBox ID="txtDateOfBirth" runat="server" TextMode="Date"></asp:TextBox>
                        </td>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td>
                            <asp:Button ID="btnAddUser" runat="server" Text="Add User" OnClick="btnAddUser_Click" />
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
        <!-- End Of Add User Form -->
        <div>
            <asp:Label ID="lblError" runat="server" CssClass="errorMsg"></asp:Label>
        </div>

        <asp:Panel ID="panelConfirmDelete" runat="server" Visible="False">
            <label>Are you sure to delete user?</label>
            &nbsp;
            <asp:Button ID="btnSureToDeleteUser" runat="server" Text="Yes" CssClass="confirmButton" OnClick="btnSureToDeleteUser_Click" />
            &nbsp;
            <asp:Button ID="btnCancelDeleteUser" runat="server" Text="No" CssClass="confirmButton" OnClick="btnCancelDeleteUser_Click" />
        </asp:Panel>
        <div>
            <asp:GridView ID="gridUsers" runat="server" AutoGenerateColumns="False" DataKeyNames="UserID" DataSourceID="dataSourceUsers" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowDeleting="gridUsers_RowDeleting" OnRowUpdating="gridUsers_RowUpdating">
                <Columns>
                    <asp:BoundField DataField="UserID" HeaderText="User ID" ReadOnly="True" InsertVisible="False" SortExpression="UserID"></asp:BoundField>
                    <asp:BoundField DataField="UserName" HeaderText="User Name" SortExpression="UserName"></asp:BoundField>
                    <asp:BoundField DataField="Email" HeaderText="Email" SortExpression="Email"></asp:BoundField>
                    <asp:BoundField DataField="BirthData" HeaderText="Date Of Birth" SortExpression="BirthData"></asp:BoundField>
                </Columns>
            </asp:GridView>
        </div>
        <asp:SqlDataSource
            ID="dataSourceUsers"
            runat="server"
            ConnectionString='<%$ ConnectionStrings:CompanyConnectionString %>'
            SelectCommand="SELECT * FROM [Users]" 
            DeleteCommand="DELETE FROM [Users] WHERE [UserID] = @UserID" 
            InsertCommand="INSERT INTO [Users] ([UserName], [Email], [BirthData]) VALUES (@UserName, @Email, @BirthData)" 
            UpdateCommand="UPDATE [Users] SET [UserName] = @UserName, [Email] = @Email, [BirthData] = @BirthData WHERE [UserID] = @UserID"
            >
            <DeleteParameters>
                <asp:Parameter Name="UserID" Type="Int32"></asp:Parameter>
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="UserName" Type="String"></asp:Parameter>
                <asp:Parameter Name="Email" Type="String"></asp:Parameter>
                <asp:Parameter Name="BirthData" Type="DateTime"></asp:Parameter>
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="UserName" Type="String"></asp:Parameter>
                <asp:Parameter Name="Email" Type="String"></asp:Parameter>
                <asp:Parameter Name="BirthData" Type="DateTime"></asp:Parameter>
                <asp:Parameter Name="UserID" Type="Int32"></asp:Parameter>
            </UpdateParameters>
        </asp:SqlDataSource>
    </form>
</body>
</html>
